- tab-cli/src/lib.rs
- tab/src/cli.rs
> Select the `any` tab if no arguments are provided

- tab-daemon/src/service/cli.rs
- tab/tests/common/mod.rs
- Override the TAB and TAB_ID vars for the invoked test
- Fix a synchronization bug with Retask, that caused scrollback not to be echoed.  This was causing the switch test to time out on github actions.
> Add a timeout in case an integration test blocks on the read

- Cargo.lock
- Cargo.toml
- RELEASE-CHECKLIST.md
- tab-command/src/service/workspace.rs
- tab-command/src/state/workspace.rs
Add support for nested workspaces, and links from a workspace in your home directory to child workspaces.
- When the user is within a workspace, tab will render all repo, workspace, and tab literals defined in the workspace config.
- Tab will search for workspaces up to the root directory.
- When a workspace contains a repo link to an existing directory, but no tab.yml exists there, a tab will be rendered with the directory name and working dir.
Resolves #138 
Resolves #148
> Support nested workspaces - a method for lateral navigation between workspaces

- common/tab-api/src/tab.rs
- tab-command/src/bus/tab.rs
- tab-command/src/service/create_tab.rs
- tab-command/src/service/workspace.rs
- tab-command/src/state/workspace.rs
- tab-daemon/src/bus/cli.rs
- tab-daemon/src/service/cli.rs
- tab-daemon/src/service/pty.rs
- tab-pty/src/service/client.rs
- Add `env`, a map property that can be set for any tab.
- Add `shell`, a string property that can be set for any tab.
- Add inheritance to repo tabs (between the root tab, and subtabs)
- Add inheritance to workspace tabs (between the root tab, and inline workspace tabs)
> Add configurable shells and environment variables

- Cargo.lock
- common/tab-api/src/config.rs
- tab-command/Cargo.toml
- tab-command/src/lib.rs
- tab-daemon/src/lib.rs
- tab-daemon/src/service/daemon/listener.rs
- tab/src/main.rs
If the tab command client version differs from the daemon (ignoring patch versions), then a message is printed recommending that `tab --shutdown` be invoked.
If the tab binary path differs from the daemon executable, then a message is printed suggesting that `tab --shutdown` be invoked.
> Add incompatibility warnings if the tab binary or version differs

- tab-command/src/service/workspace.rs
Until `tab --check` is implemented, clean up the UX on a workspace parse error.
Instead of repeatedly logging errors, only log once.
> Only log workspace errors once

- common/tab-api/src/tab.rs
- tab-command/src/service/tab/create_tab.rs
- tab-command/src/state/workspace.rs
- tab-daemon/src/bus/cli.rs
- tab-daemon/src/service/cli.rs
- tab-daemon/src/service/pty.rs
- tab-pty/src/service/client.rs
Remember tab docstrings for workspace tabs after navigating away from the workspace.
Resolves #190
> Remember tab docstrings

- tab-command/src/service/tab/workspace.rs
- tab-command/src/service/tab/workspace/loader.rs
- tab-command/src/service/tab/workspace/repo.rs
- tab-command/src/service/tab/workspace/workspace.rs
- tab-command/src/state/workspace.rs
- tab-command/test_resources/dir/tab.yml
- tab-command/test_resources/doc/tab.yml
- tab-command/test_resources/env/tab.yml
- tab-command/test_resources/shell/tab.yml
Split up the workspace loader, and write a TabIter to clean up the code
> Clean up the workspace loader implementation

- common/tab-api/src/tab.rs
- tab-command/src/lib.rs
- tab-command/src/message/main.rs
- tab-command/src/service/main.rs
- tab-command/src/service/main/check_workspace.rs
- tab-command/src/service/tab/workspace.rs
- tab-command/src/service/tab/workspace/loader.rs
- tab-command/src/service/tab/workspace/repo.rs
- tab-command/src/service/tab/workspace/workspace.rs
- tab-command/src/state.rs
- tab-command/src/state/workspace.rs
- tab-command/src/state/workspace_err.rs
- tab/src/cli.rs
- tab/src/completions/bash/tab.bash
- tab/src/completions/fish/tab.fish
- tab/src/completions/zsh/_tab
Implement `tab --check`, a utility that prints errors and warnings about tab.yml configurations.
Example:
```
$ tab --check
4 errors were detected:
- Tab tab/foo/ has a working directory that does not exist: /Users/austinjones/workspace/tab-rs/not-exists/
- Workspace path does not exist: /Users/austinjones/workspace/../not-exists
- Repository path does not exist: /Users/austinjones/workspace/not-exists
- Tab duplicate/ has duplicate definitions
```
> Implement `tab --check`, a workspace validation utility

- common/tab-api/src/launch.rs
- tab-command/src/bus/tab.rs
- tab-command/src/bus/terminal.rs
- tab-command/src/lib.rs
- tab-command/src/message/main.rs
- tab-command/src/service/main/autocomplete_close_tab.rs
- tab-command/src/service/main/autocomplete_tab.rs
- tab-command/src/service/main/check_workspace.rs
- tab-command/src/service/main/close_tabs.rs
- tab-command/src/service/main/disconnect_tabs.rs
- tab-command/src/service/main/global_shutdown.rs
- tab-command/src/service/main/list_tabs.rs
- tab-daemon/src/message/daemon.rs
- tab-pty/src/message/pty.rs
- tab/src/main.rs
If `tab --close` or `tab --disconnect` are provided no args, they fall back to closing the current tab.  If no current tab is detected, return exit code 1.
> Support exit codes in tab-command, and return 1 if close or disconnect have no args

- common/tab-api/src/config.rs
- common/tab-api/src/launch.rs
- tab-command/src/service/tab/tab_state.rs
- tab-command/src/service/terminal/echo_mode.rs
- tab-command/src/service/terminal/fuzzy.rs
- tab-daemon/src/bus/cli.rs
- tab-daemon/src/bus/pty.rs
- tab-daemon/src/service/cli.rs
- tab-daemon/src/service/cli/subscription.rs
- tab-daemon/src/service/daemon/tab_assignment.rs
- tab-daemon/src/service/pty.rs
- tab-pty/src/lib.rs
- tab-pty/src/service/client.rs
Bugfixes:
- In debug mode, the PTY sometimes failed to initialize because the PtyWebsocketRequest receiver did not catch the Init message.
- In Ubuntu, the alternate screen reset caused bash to repaint over existing text.
- The Fuzzy Finder sometimes failed to clear the screen, as there was no synchronization between the selection event that triggered the repaint, and the output task.  Now the selection task holds the output lifeline, and drops it when sending a selection/termination message.
- There was no PTY log!  Added `pty.log` to the data_dir() tab folder.  Each pty will truncate the log, so this is intended for debugging.
> Fix several 0.5 bugs and a debug mode timing bug

- Cargo.lock
- Cargo.toml
- tab-command/src/service/terminal/echo_mode.rs
- tab-daemon/src/service/pty/scrollback.rs
Fix two issues that caused rendering corruption when interactive editors (neovim, kakoune) were used within a tab session.
- Neovim & Kakoune experienced corruption when reconnecting an active session, due to an insufficient MIN_CAPACITY constant in the scrollback buffer.  The new default is 128MB of scrollback which is enough for about 6000 scrolls through the tab README.md file.  In the future, I'm going to look at compressing the scrollback buffer by pruning stdout that has been repainted.
- Kakoune experienced cursor corruption when moving the cursor on the 2nd/3rd/nth column.  This was caused by an incorrect `\n' character being inserted by the tab-command TerminalEchoMode service.
Resolves #226
> Fix a few subtle bugs that caused corruption during interactive editor sessions

- .github/workflows/release.yml
The homebrew job builds a separate OSX binary, and that is getting all the downloads.
> Remove apple-darwin from release matrix, as it isn't getting any downloads and it's failing

- Cargo.lock
- Cargo.toml
- tab-command/src/bus/tab.rs
- tab-command/src/service/tab/create_tab.rs
- tab-command/src/service/tab/tab_state.rs
- tab-daemon/src/service/cli.rs
TerminalSizeState was carried on the TabBus, but it was not updated.  Removed from the TabBus and replaced with crate::env::terminal_size()
> Fix a resize bug that affected resumed retask sessions

- tab-command/src/service/main/list_tabs.rs
I am not 100% sure this is the intended behaviour of #51, but here is how I envisioned it based on the description.
`tab -l`
`tab foo`
`tab tab-rs`
> adding active indicator

- Cargo.lock
- Cargo.toml
- common/tab-api/src/config.rs
The issue here was that across reboots, the daemon pidfile could refer to a new process - not the daemon!  In that case, tab wouldn't clear the pidfile and relaunch the daemon.
This PR introduces logic to check that `--_launch daemon` is in the command string provided by sysinfo.
I did not check that `tab` is in the command, as tab could be installed as any executable name.
> Fix a bug where the daemon pidfile refers to a process which is running, but isn't the daemon.

- Cargo.lock
- Cargo.toml
- tab-command/src/service/terminal/echo_mode.rs
- tab-daemon/src/service/daemon/listener.rs
- tab-pty/src/service/pty.rs
Changes:
- Limit the stdout max packet rate to 0.15ms
- Increase the PtyWebsocketResponse buffer size in the daemon to 128 packets.
Impact:
- Reduces CPU usage when using interactive apps that generate high frequency update events
- Fixes a rendering corruption issue (#268) when kakoune is used with relative line numbers (`add-highlighter global/ number-lines -relative` in kakrc).
> Reduce CPU consumption and fix a rendering corruption issue with kakoune relative line numbers

- Cargo.toml
This reduces release-mode binary size from 15.7mb to 11mb.
A further manual call to `strip` reduces the binary to 8.4mb, and hopefully the `cargo` patch to run `strip` automatically will be included soon.
> Link-time Optimization

- Cargo.toml
- tab-command/src/message/fuzzy.rs
- tab-command/src/service/terminal/fuzzy.rs
- tab-command/src/state/fuzzy.rs
Add a `(new tab)` option to the fuzzy finder, that is presented if:
- The user has entered a query that does not conflict with an existing tab.
- The user has no tab entries (e.g. no YAML configs and no running tabs).
Refactor tab name/doc matching.  Some of the name/doc code has been made more generic, and doc indentation happens later in the pipeline.
TabEntry now has a `sticky` property.  Sticky entries are always matched, and have the entire tab name underlined.  Sticky entries are sorted to the end of the list.
Also add bindings for PageUp/PageDown.
> Create new tabs in the fuzzy finder!

- tab-command/src/lib.rs
- tab-command/src/service/terminal.rs
- tab-command/src/service/terminal/echo_mode.rs
- tab-command/src/service/terminal/fuzzy.rs
There have been several recent bug reports that relate to incorrect terminal state resets when the tab client is disconnected.  Resets on disconnects are necessary, because I allow TUI apps to set any state they want in the connected terminal emulator.
I preferred only resetting the state that was necessary, but I think a full reset is needed due to recent bug reports.
> Refactor terminal resets

- tab-command/src/lib.rs
- tab-command/src/service/main/select_tab.rs
- tab-command/src/service/terminal.rs
- tab-command/src/service/terminal/echo_mode.rs
- tab-command/src/service/terminal/fuzzy.rs
- tab-command/src/state/terminal.rs
- More consistently apply terminal resets when switching tabs, or opening the fuzzy finder.  The TerminalService now executes resets if EchoMode has been activated.  And resets when switching tabs.
- Change the reset sequence to `ESC c ESC [ 2 J` - reset then clear.  The clear is needed for the prompt to show up.
- Sometimes the tab-command client didn't shut down due to `shutdown_background` never returning.
> More improvements to terminal resets

- tab-command/src/bus/tab.rs
- tab-command/src/service/main/select_tab.rs
- tab-command/src/service/terminal.rs
- tab-command/src/service/terminal/echo_mode.rs
- tab-command/src/service/terminal/fuzzy.rs
- tab-command/src/state/terminal.rs
- Trigger Echo mode resets when a new TabId is selected.  This more consistently applies terminal resets (e.g. during retasks or fuzzy selections).
- Only respawn the Echo / Fuzzy services if the terminal mode discriminant changes.  This avoids re-initializing the stdin reference, which caused a bug where the first character typed after a retask did nothing.
> Improve terminal state management.  Only restart services if mode discriminant changes

- Cargo.lock
- tab-daemon/src/service/pty/scrollback.rs
From the bash (Apple) terminal, I'd ~sometimes get:
```
[>1;95;0c
```
The filter works great! I don't see them any more in my local build.
> filter more control sequences (polluting the terminal)

- Cargo.lock
- Cargo.toml
- common/tab-api/Cargo.toml
- common/tab-api/src/launch.rs
This resolves #313, by forking the process when launching the daemon.  This prevents the daemon from being reaped if:
- The tab command was launched by a parent process.
- The tab command exited.
- The parent called [std::process::Child::try_wait](https://doc.rust-lang.org/std/process/struct.Child.html#method.try_wait) on the tab command handle.
> Use `nix` to fork the process when launching the daemon

- tab-command/src/bus/fuzzy.rs
- tab-command/src/bus/main.rs
- tab-command/src/bus/tab.rs
- tab-command/src/service/main/select_interactive.rs
- tab-command/src/service/main/select_tab.rs
- tab-command/src/service/terminal.rs
- tab-command/src/service/terminal/echo_input.rs
- tab-command/src/service/terminal/fuzzy.rs
- tab-command/src/state/fuzzy.rs
- tab-command/src/state/tab.rs
- tab-command/src/state/terminal.rs
- tab/tests/common/mod.rs
- tab/tests/retask.rs
`ctrl-c` can now be used to quit the fuzzy finder.
> Rebind `ESC` in the fuzzy finder to return to the previously selected tab

- common/tab-api/src/client.rs
- tab-command/src/bus/tab.rs
- tab-command/src/service/main.rs
- tab-command/src/service/main/select_interactive.rs
- tab-command/src/service/main/select_tab.rs
- tab-command/src/service/tab/select_tab.rs
- tab-daemon/src/bus/cli.rs
- tab-daemon/src/message/cli.rs
- tab-daemon/src/message/tab.rs
- tab-daemon/src/service/cli.rs
- tab-daemon/src/service/cli/subscription.rs
- tab-daemon/src/service/daemon/retask.rs
- tab/tests/keyboard_latency.rs
This PR allows users to execute `tab` with no arguments within a session.  The outer tab client will retask to the fuzzy finder.
> Add 'fuzzy finder' retask support

- tab-command/src/lib.rs
- tab-command/src/message/main.rs
- tab-command/src/service/main.rs
- tab-command/src/service/main/select_previous.rs
- tab/src/cli.rs
When outside a session, it switches to the most recently selected tab:
```
$ tab foo
foo/ $ <disconnect>
$ tab -
foo/ $
```
When within a session, it switches to the previously selected tab
```
$ tab foo
foo/ $ tab bar
bar/ $ tab -
foo/ $
```
> Add `tab -` that selects the previous tab
